IK-280TS
imagekitio/docs-keep-a-changelog pull request #232
Opened 2023-12-21 07:25 UTC by yashaswi-imagekit

2024-01-30 08:34 UTC, ahnv requested changes

2024-01-30 08:34 UTC, ahnv commented on features/image-transformations/README.md
> +Here we have put the ImageKit.io logo ([https://ik.imagekit.io/demo/logo-white\_SJwqB4Nfe.png](https://ik.imagekit.io/demo/logo-white\_SJwqB4Nfe.png)) on another image using overlay syntac i.e. `l-im
```suggestion
Here we have put the ImageKit.io logo ([https://ik.imagekit.io/demo/logo-white\_SJwqB4Nfe.png](https://ik.imagekit.io/demo/logo-white\_SJwqB4Nfe.png)) on another image using layer overlay syntax i.e. `l-image,i-logo-white_SJwqB4Nfe.png,l-end`
```

2024-01-30 08:34 UTC, ahnv commented on features/image-transformations/README.md
> +![https://ik.imagekit.io/demo/tr:h-300l-image,i-logo-whit\_SJwqB4Nfe.png,l-end/medium\_cafe\_B1iTdD0C.jpg](../../.gitbook/assets/overlay-image.jpg)
URL not working

2024-02-24 15:33 UTC, imagekitio commented
made changes in master.

2024-02-24 15:33 UTC, closed without merging