react-native quick start guide
imagekitio/docs-keep-a-changelog pull request #235
Opened 2023-12-25 03:25 UTC by ankur-dwivedi

2024-01-02 11:04 UTC, eclectic-memory reviewed
A few minor changes are needed. Overall looks fine.

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +```bash
Can we list all the packages in a single command instead of separate ones? Something like:

```
npm install package1 \
package2 \
package3
```

This was the user won't have to run multiple commands. Most terminals don't copy multiple lines at once properly AFAIK.

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +In the sample app, we are using our own custom `Button` components created using React native's components for consistency, you can use them, original or any other UI kit if you want.
> you can use them, original or any other UI kit if you want.

"original" is slightly confusing here. I'm assuming you mean this: https://reactnative.dev/docs/button

Would saying the core component button provided by RN be more clear?

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  * [Setting up Imagekit Javascript SDK](react-native.md#setting-up-imagekit-javascript-sdk)
Can we replace `Imagekit` by `ImageKit` throughout this document?

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
IIRC a lot of RN devs use Expo. Do we need to add it here specifically or would the instructions be the same for Expo users too?

Ref: https://expo.dev/

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  ## **Setting up Imagekit Javascript SDK**
Should we suggest installing the `react-native-url-polyfill` by default & remove the additional hint in this section considering that all future versions will need it?

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  And now to run the app in the ios simulator (you should have Xcode installed)
```suggestion
And now to run the app in the iOS simulator (you should have Xcode installed)
```

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +In the sample app, we are using our own custom `Button` components created using React native's components for consistency, you can use them, original or any other UI kit if you want.
We can also choose to not mention this altogether. It should be understood that the user can use their own UI components.

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
Compared to the iOS tutorial where we just cloned the sample app and just parameters, we're making the user copy paste multiple components one by one even though those components don't have anything specific to do with the ImageKit integration (like the Button, the Main screen etc.). Why're we not starting from a sample app here?

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +export default AppComponent;
Formatting in code-blocks is slightly inconsistent across the entire tutorial.
```
import { createStackNavigator } from '@react-navigation/stack';
import {createStackNavigator} from '@react-navigation/stack';
```

```
return (
		<Stack.Navigator>
			<Stack.Screen name="Home" component={Main} />
		</Stack.Navigator>
	);
	
return (
    <Stack.Navigator>
      <Stack.Screen name="Home" component={Main} />
    </Stack.Navigator>
  );
  
```

This shouldn't be a major issue though IMO so it can be ignored.

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +module.exports.authenticationEndpoint = authenticationEndpoint;
```suggestion
module.exports.urlEndpoint = ""; //insert your own url end point here
module.exports.publicKey = ""; //insert your own public key here
module.exports.authenticationEndpoint = ""; //your auth api path, currently set to demo server included with this project
```

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  {% code title="app/lib/imagekit.js" %}
In `app/lib/imagekit.js`, is some sort of validation run for empty `publicKey` & `authenticationEndpoint` parameter?

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +	var imageURL = imagekit.url(ikOptions);
Can we use `const` or `let` instead of `var` wherever possible across the entire tutorial?

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +Now, lets create `app/screens/Fetch/index.js` to fetch an image also lets update `app/AppComponent.js` to include fetch image screen.
```suggestion
Now, lets create `app/screens/Fetch/index.js` to fetch an image. Also, update `app/AppComponent.js` to include the fetch image screen.
```

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  ## Common Image Manipulation
We're mentioning the React SDK in this section. I'm not sure if it has anything to do with the React Native tutorial since we're using the JavaScript SDK in this case.

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +<div style="display: flex; flex-direction:row;justify-content: center;">
```suggestion
<div style="display:flex; flex-direction:row; justify-content:center;">
```

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +	<img src="../../.gitbook/assets/react-nativet2.PNG" alt="React native crop mode" width="300"/>
```suggestion
	<img src="../../.gitbook/assets/react-nativet2.PNG" alt="React Native crop mode" width="300"/>
```

Please do a find & replace on the entire document so that we're using the same letter case everywhere.

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +We will use the[ ImageKit Node.js SDK](https://github.com/imagekit-developer/imagekit-nodejs) to implement `http://localhost:3001/auth`.
```suggestion
We will use the [ImageKit Node.js SDK](https://github.com/imagekit-developer/imagekit-nodejs) to implement `http://localhost:3001/auth`.
```

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +You should see a log saying that the app is _**“Live on port 3001”**_.
In the code, we're using port 8080.

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +npm install --save express uuid dotenv cors
`--save` isn't needed now IIRC. The packages are saved under dependencies by default as of npm 5.0.0 which was released in 2017. 
We should remove the --save flag across this document.

Ref: https://blog.npmjs.org/post/161081169345/v500

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +const privateKey = process.env.PRIVATE_KEY;
I think we should directly put the private key here (as `""`) like most tutorials do since we're just trying to get an app up and running.
It'd also save the user from installing the `dotenv` dependency while trying out ImageKit for their app & remove a small section from this tutorial.

2024-01-02 11:04 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +    });
```suggestion
    res.send({
        token,
        expire,
        signature
    });
```

2024-01-02 11:14 UTC, imagekitio commented on getting-started/quickstart-guides/react-native.md
> +export default AppComponent;
Formatting matters. It should be consistent.

2024-01-03 01:13 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +```bash
done

2024-01-03 01:14 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +In the sample app, we are using our own custom `Button` components created using React native's components for consistency, you can use them, original or any other UI kit if you want.
updated the above line

2024-01-03 01:14 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
>  * [Setting up Imagekit Javascript SDK](react-native.md#setting-up-imagekit-javascript-sdk)
done

2024-01-03 01:14 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
>  And now to run the app in the ios simulator (you should have Xcode installed)
done

2024-01-03 01:15 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +export default AppComponent;
done formatted the code

2024-01-03 01:15 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +module.exports.authenticationEndpoint = authenticationEndpoint;
done

2024-01-03 01:16 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +	var imageURL = imagekit.url(ikOptions);
done  updated the code and docs

2024-01-03 01:16 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +Now, lets create `app/screens/Fetch/index.js` to fetch an image also lets update `app/AppComponent.js` to include fetch image screen.
done

2024-01-03 01:17 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
>  ## Common Image Manipulation
done removed React SDK it should be Javascript SDK

2024-01-03 01:17 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +<div style="display: flex; flex-direction:row;justify-content: center;">
done

2024-01-03 01:17 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +	<img src="../../.gitbook/assets/react-nativet2.PNG" alt="React native crop mode" width="300"/>
done

2024-01-03 01:17 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +We will use the[ ImageKit Node.js SDK](https://github.com/imagekit-developer/imagekit-nodejs) to implement `http://localhost:3001/auth`.
done

2024-01-03 01:18 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +You should see a log saying that the app is _**“Live on port 3001”**_.
done updated it

2024-01-03 01:18 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +npm install --save express uuid dotenv cors
done removed `--save`

2024-01-03 01:18 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +    });
done

2024-01-03 01:20 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
I had discussion on it with had similar doubt, we decided to move in the current direction like creating app from scratch

2024-01-03 01:22 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
>  ## **Setting up Imagekit Javascript SDK**
I think it's better to give the user information on why they need to install `react-native-url-polyfill `.  So I think above hint would be helpful.

2024-01-03 03:25 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
>  {% code title="app/lib/imagekit.js" %}
There is a check for `publicKey` and `authenticationEndpoint` these if they are present then only we are passing it to config options 
```suggestion
{% code title="app/lib/imagekit.js" %}
const imagekitConfigOptions = {urlEndpoint};
if (publicKey) imagekitConfigOptions.publicKey = publicKey;
if (authenticationEndpoint)
  imagekitConfigOptions.authenticationEndpoint = authenticationEndpoint;

const imagekit = new ImageKit(imagekitConfigOptions);
```

2024-01-03 03:25 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
>  {% code title="app/lib/imagekit.js" %}
There is a check for `publicKey` and `authenticationEndpoint` these if they are present then only we are passing it to config options 
```suggestion
{% code title="app/lib/imagekit.js" %}
const imagekitConfigOptions = {urlEndpoint};
if (publicKey) imagekitConfigOptions.publicKey = publicKey;
if (authenticationEndpoint)
  imagekitConfigOptions.authenticationEndpoint = authenticationEndpoint;

const imagekit = new ImageKit(imagekitConfigOptions);
```

2024-01-03 03:38 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +const privateKey = process.env.PRIVATE_KEY;
done

2024-01-03 04:37 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
regarding `expo` the only difference would be setting up an expo environment for running the application. The rest of our react-native application would be the same.

2024-01-03 14:30 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  ## **Setting up Imagekit Javascript SDK**
Alright.

2024-01-03 15:01 UTC, eclectic-memory requested changes
Some minor changes are requested.

2024-01-03 15:01 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +And now to run the app in the IOS simulator (you should have Xcode installed)
```suggestion
And now to run the app in the iOS simulator (you should have Xcode installed)
```

2024-01-03 15:01 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +You should see a log saying that the app is _**“Live on port 8080”**_.
```suggestion
You should see a log saying that the app is _**'Live at Port 8080'**_.
```

2024-01-03 15:01 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  #### **Configure the auth endpoint in the frontend app**
<img width="739" alt="image" src="https://github.com/imagekitio/docs-keep-a-changelog/assets/141143550/261b392e-c109-4061-b60f-2b92324429c6">

See the highlighted part.

2024-01-03 15:01 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +* [Setting up react-native app](react-native.md#setting-up-react-native-app)
```suggestion
* [Setting up the React Native app](react-native.md#setting-up-the-react-native-app)
```

Please make the same change in the heading too.

2024-01-03 15:01 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +module.exports.authenticationEndpoint = ''; //your auth api path, currently set to demo server included with this project
```suggestion
module.exports.authenticationEndpoint = ''; //your auth api path
```

I think we should mention that we'll set it to the demo server endpoint in this tutorial. 
We haven't done it yet so saying that "currently set to demo server" doesn't make sense.

2024-01-03 15:01 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +      case 'Transformation 3': //aspect ration and url from path and transformations as query param
```suggestion
      case 'Transformation 3': //aspect ratio and url from path and transformations as query param
```

2024-01-03 15:01 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  ### Aspect Ratio
<img width="702" alt="image" src="https://github.com/imagekitio/docs-keep-a-changelog/assets/141143550/1d9fa460-f154-495d-ba5d-2ec23d5464f8">

See the `**:**`.

2024-01-03 15:01 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +And now to run the app in the IOS simulator (you should have Xcode installed)
<img width="499" alt="image" src="https://github.com/imagekitio/docs-keep-a-changelog/assets/141143550/bce56daf-cb25-47d4-9781-32b360132e77">

2024-01-03 15:02 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +You should see a log saying that the app is _**“Live on port 8080”**_.
Need to match w/ the server log line.

2024-01-03 16:25 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +And now to run the app in the IOS simulator (you should have Xcode installed)
done

2024-01-03 16:26 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +You should see a log saying that the app is _**“Live on port 8080”**_.
done

2024-01-03 16:28 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
>  #### **Configure the auth endpoint in the frontend app**
done

2024-01-03 16:28 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +* [Setting up react-native app](react-native.md#setting-up-react-native-app)
done

2024-01-03 16:28 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +module.exports.authenticationEndpoint = ''; //your auth api path, currently set to demo server included with this project
done

2024-01-03 16:29 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +      case 'Transformation 3': //aspect ration and url from path and transformations as query param
done

2024-01-03 16:30 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
>  ### Aspect Ratio
done

2024-01-03 19:14 UTC, eclectic-memory requested changes

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +In the sample app, we are using our own custom `Button` components created using React Native's components to ensure consistency.
```suggestion
In the sample app, we are using our own custom `Button` component created using React Native's components to ensure consistency.
```

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +## **Setting up react-native app**
Please make the heading same the the text linking to it above.

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +Create `index.js` and `styles.js` files within the `app/screens/Main` directory. These files will incorporate buttons facilitating navigation to different screens, which will be developed in the subs
```suggestion
Create `index.js` and `styles.js` files within the `app/screens/Main` directory. These files will render & style buttons facilitating navigation to different screens, which will be developed in the subsequent sections. This configuration serves as our home screen.
```

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +Create `index.js` and `styles.js` files within the `app/screens/Main` directory. These files will incorporate buttons facilitating navigation to different screens, which will be developed in the subs
Could also use `have` instead. Just trying to use simpler (and technical) English words.

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +Create the `AppComponent.js` file within the `app` directory, encompassing the screens. Initiate with the home screen. Additionally, open the `App.tsx` file and include the provided code to render th
```suggestion
Create the `AppComponent.js` file within the `app` directory which will contain the screens. Add the home screen.
Open the `App.tsx` file and add the provided code to render the `AppComponent`.
```

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +	<img src="../../.gitbook/assets/react-native-home.PNG" alt="React Native home screen" width="300"/>
```suggestion
	<img src="../../.gitbook/assets/react-native-home.PNG" alt="React Native Home Screen" width="300"/>
```

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +We will be using [ImageKit javascript SDK](https://github.com/imagekit-developer/imagekit-javascript). So let's install it.
```suggestion
We will be using [ImageKit JavaScript SDK](https://github.com/imagekit-developer/imagekit-javascript). So let's install it.
```

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  {% hint style="warning" %}
`URL [API]` looks wrong. We should use `[URL API]` for the link since we're linking to the MDN page for that API & not for the definition of an API itself.

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  To create a URL from the image path, we can create a helper function like this below. This function takes the URL endpoint, image path, transformation array, and transformation position as parameters
The function isn't taking the URL endpoint. 

IMO we don't need to have this line explaining the function input and output. It's apparent from the code itself. 
We can just use the full name for `transformationArr` i.e. `transformationArray` & get rid of this statement.

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  To create a URL from the image path, we can create a helper function like this below. This function takes the URL endpoint, image path, transformation array, and transformation position as parameters
Note: If you end up renaming `transformationArr`, do it through the entire doc.

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +Now, lets create `app/screens/Fetch/index.js` to fetch an image. Also, update `app/AppComponent.js` to include the fetch image screen.
```suggestion
Now, let's create `app/screens/Fetch/index.js` to fetch an image. Also, update `app/AppComponent.js` to include the fetch image screen.
```

"lets" is letting someone do a thing
"let's" is short for let us

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +Now, lets create `app/screens/Fetch/index.js` to fetch an image. Also, update `app/AppComponent.js` to include the fetch image screen.
Check the lets vs. let's thing at other places in the document too. I think you meant to use `let's` but used `lets` in a few places due to typo.

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +	<img src="../../.gitbook/assets/react-nativet1.PNG" alt="React Native basic image resizing" width="300"/>
```suggestion
	<img src="../../.gitbook/assets/react-nativet1.PNG" alt="React Native Basic Image Resizing" width="300"/>
```

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
different crop mode works -> different crop modes work

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
Also, add a linebreak after the end of 1st statement. The paragraph is quite long.

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
We say that we're going to see how different crop modes work but just end up showing a single crop mode.

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
Line 742

`Text overlay can be used to superimpose text on an image. Try it like so:`

Change to:
`Text overlay can be used to place text on an image. Here's how:`

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +	<img src="../../.gitbook/assets/react-native-home.PNG" alt="React Native home screen" width="300"/>
Make the change in other places too.

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +For this, let's create couple of functions in `app/lib/imagekit.js` file and also lets update `app/AppComponent.js` to include upload screen.
```suggestion
For this, let's create couple of functions in `app/lib/imagekit.js` file and update `app/AppComponent.js` to include the upload screen.
```

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  If you don't see the file, check if there are any errors in the browser console log. Make sure that the private API key has been configured. The server app is running. And the uploaded file type is [
`browser console log`? The user was running the app on their emulator, right? So they'd see the error there.

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +To play a video file, a video player is required. In this context, we are utilizing `react-native-video`, but feel free to choose any video player of your preference.
```suggestion
We're going to use the `react-native-video` package to play video files, but you can use any other video player.
```

Also, link the npm package.

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
> +This is how we fetch videos in `app/screens/Videos/index.js` and also lets update `app/AppComponent.js` to include video fetch screen.
```suggestion
Update the `app/screens/Videos/index.js` and `app/AppComponent.js` file to fetch video.
```

2024-01-03 19:14 UTC, eclectic-memory commented on getting-started/quickstart-guides/react-native.md
>  For selecting a file, we will need a picker. Here we are using `react-native-document-picker` but you can use any picker.
```suggestion
We are going to use `react-native-document-picker` to select files.
```

2024-01-03 19:55 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +In the sample app, we are using our own custom `Button` components created using React Native's components to ensure consistency.
done

2024-01-03 19:59 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +## **Setting up react-native app**
done

2024-01-03 20:00 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +Create `index.js` and `styles.js` files within the `app/screens/Main` directory. These files will incorporate buttons facilitating navigation to different screens, which will be developed in the subs
done

2024-01-03 20:01 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +Create the `AppComponent.js` file within the `app` directory, encompassing the screens. Initiate with the home screen. Additionally, open the `App.tsx` file and include the provided code to render th
done

2024-01-03 20:01 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +	<img src="../../.gitbook/assets/react-native-home.PNG" alt="React Native home screen" width="300"/>
done

2024-01-03 20:01 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +We will be using [ImageKit javascript SDK](https://github.com/imagekit-developer/imagekit-javascript). So let's install it.
done

2024-01-03 20:05 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
>  {% hint style="warning" %}
done

2024-01-03 20:06 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +Now, lets create `app/screens/Fetch/index.js` to fetch an image. Also, update `app/AppComponent.js` to include the fetch image screen.
done

2024-01-03 20:07 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +	<img src="../../.gitbook/assets/react-nativet1.PNG" alt="React Native basic image resizing" width="300"/>
done

2024-01-03 20:07 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
done

2024-01-03 20:08 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +For this, let's create couple of functions in `app/lib/imagekit.js` file and also lets update `app/AppComponent.js` to include upload screen.
done

2024-01-03 20:08 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
>  If you don't see the file, check if there are any errors in the browser console log. Make sure that the private API key has been configured. The server app is running. And the uploaded file type is [
yes updated it to `If you don't see the file, check if there are any errors in the log.`

2024-01-03 20:09 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +To play a video file, a video player is required. In this context, we are utilizing `react-native-video`, but feel free to choose any video player of your preference.
done

2024-01-03 20:10 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
> +This is how we fetch videos in `app/screens/Videos/index.js` and also lets update `app/AppComponent.js` to include video fetch screen.
done

2024-01-03 20:10 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
>  For selecting a file, we will need a picker. Here we are using `react-native-document-picker` but you can use any picker.
done

2024-01-03 20:22 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
done updated the message also

2024-01-03 20:42 UTC, ankur-dwivedi commented on getting-started/quickstart-guides/react-native.md
>  To create a URL from the image path, we can create a helper function like this below. This function takes the URL endpoint, image path, transformation array, and transformation position as parameters
done

2024-01-04 05:58 UTC, eclectic-memory approved these changes

2024-01-09 06:35 UTC, merged