Webhook signature docs
imagekitio/docs-keep-a-changelog pull request #49
Opened 2022-07-01 11:22 UTC by rishavbhowmik

- Updated screen short with, 'webhook secret' changes
- `## Verify webhook signature`
- `## Preventing replay attacks`

2022-07-04 05:43 UTC, imagekitio requested changes

2022-07-04 05:43 UTC, imagekitio commented on api-reference/api-introduction/webhooks.md
> +```js
We need to mention that it comes in header. Be verbose. Show it in context.

2022-07-04 05:43 UTC, imagekitio commented on api-reference/api-introduction/webhooks.md
> +hmac = 'v1=b6bc2aa82491c32f1cbef0eb52b7ffaa51467ea65a03b5d4ccdcfb9e0941c946'.split('=')[1]
dont' use work hmac here. say it `signature`

2022-07-04 05:43 UTC, imagekitio commented on api-reference/api-introduction/webhooks.md
> +If timestamp is within the tolerance limit, the request can be considered as valid, else the request must be stalled.
Must be stalled? or ignored?

2022-07-04 05:43 UTC, imagekitio commented on api-reference/api-introduction/webhooks.md
> +> Optionally, a stronger approach is to use a nonce to prevent replay attacks. You can use Event ID as nonce, it is guaranteed to be unique across all events.
Write it as a normal paragraph.

2022-07-04 05:43 UTC, imagekitio commented on api-reference/api-introduction/webhooks.md
> +app.post("/webhook", express.raw({ type: "*/*" }), (req, res) => {
`{ type: "*/*" }` or `application/json`. We saw that that req.body was still buffer with `application/json` right?

2022-07-04 05:43 UTC, imagekitio commented on api-reference/api-introduction/webhooks.md
> -    case 'video.transformation.ready':
Please revert this change. They are more verbose and in line with our docs.

2022-07-04 05:43 UTC, imagekitio commented on api-reference/api-introduction/webhooks.md
> +        case "video.transformation.accepted":
Please keep comments as Express.

2022-07-04 11:42 UTC, imagekitio requested changes

2022-07-04 11:42 UTC, imagekitio commented on api-reference/api-introduction/webhooks.md
> +  .Key(webhookSecret)
What is `Hmac` here? It should be simple
```js
import { createHmac } from "crypto";
createHmac("sha256", webhookSecret).update(timestamp + '.' + rawRequestBody).digest("hex");
```

2022-07-07 10:09 UTC, rishavbhowmik reviewed
timestamp is number not Date object

2022-07-07 10:09 UTC, rishavbhowmik commented on api-reference/api-introduction/webhooks.md
> +  if (timestamp.getTime() + WEBHOOK_EXPIRY_DURATION < Date.now()) {
timestamp is now a number

2022-07-07 10:09 UTC, rishavbhowmik commented on api-reference/api-introduction/webhooks.md
> +      if (timestamp.getTime() + WEBHOOK_EXPIRY_DURATION < Date.now()) {
timestamp is number

2022-07-07 10:09 UTC, rishavbhowmik commented on api-reference/api-introduction/webhooks.md
> +    if (timestamp.getTime() + WEBHOOK_EXPIRY_DURATION < Date.now()) {
timestamp is number

2022-07-07 10:51 UTC, rishavbhowmik reviewed
Fixes for `## Verify webhook signature`

2022-07-07 10:51 UTC, rishavbhowmik commented on api-reference/api-introduction/webhooks.md
> +Webhook endpoints are publicly accessible, therefore is important filter out malicious requests. We recommend that you use webhook signature to verify the authenticity of the webhook request.
Grammer! 'important to filter'

2022-07-07 10:51 UTC, rishavbhowmik commented on api-reference/api-introduction/webhooks.md
> +To achieve this, every imagekit webhook endpoint comes with a signature in the request header `x-ik-signature`. To generate this signature, webhook secret is required, you can find webhook secret in
Correction! 'every imagekit webhook request'

2022-07-11 04:44 UTC, merged